# Profile default
server:
  port: 8081
spring:
  application:
    name: app-notificacao
sendgrid:
  api-key: ${SENDGRID_API_KEY}
  from-email: ${SENDGRID_EMAIL}
  from-name: ${SENDGRID_NAME}

# Profile para a AWS
---
spring:
  config:
    activate:
      on-profile: dev

# Profile para testes
---
spring:
  config:
    activate:
      on-profile: test
