# Profile default
server:
  port: 8080
spring:
  application:
    name: app-video
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driverClassName: ${DATASOURCE_DRIVER}
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: "update"
      dialect: "org.hibernate.dialect.MySQL8Dialect"
sendgrid:
  api-key: ${API-KEY-SENDGRID}
  from-email: soat.fase5.hackaton@gmail.com
  from-name: Hackaton

# Profile para a AWS
---
spring:
  config:
    activate:
      on-profile: dev

# Profile para testes
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    username: ${H2_USERNAME}
    password: ${H2_PASSWORD}
    driverClassName: org.h2.Driver
  sql:
    init:
      schema-locations: classpath:schema-test.sql
      data-locations: classpath:data-test.sql
