# Profile default
server:
  port: 8080
spring:
  application:
    name: app-video
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driverClassName: ${DATASOURCE_DRIVER}
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: "update"
      dialect: "org.hibernate.dialect.MySQL8Dialect"
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


pagamento:
  service:
    url: ${URL_SERV_PAGAMENTO}

# Profile para a AWS
---
spring:
  config:
    activate:
      on-profile: dev

# Profile para testes
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    username: ${H2_USERNAME}
    password: ${H2_PASSWORD}
    driverClassName: org.h2.Driver
  sql:
    init:
      schema-locations: classpath:schema-test.sql
      data-locations: classpath:data-test.sql
